// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageError(arg1) {
  return window['go']['main']['App']['MessageError'](arg1);
}

export function MessageInfo(arg1) {
  return window['go']['main']['App']['MessageInfo'](arg1);
}
