// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageError(arg1:string):Promise<Error>;

export function MessageInfo(arg1:string):Promise<Error>;
