// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';

export function ApplySettings(arg1:base.SpotifySettings):Promise<Error>;

export function GetSettings():Promise<base.SpotifySettings>;

export function ImportLikedTracks(arg1:Array<base.Track>):Promise<Error>;

export function Ping():Promise<Error>;

export function WebAuth():Promise<Error>;
