// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySettings(arg1) {
  return window['go']['main']['SpotifyApp']['ApplySettings'](arg1);
}

export function GetSettings() {
  return window['go']['main']['SpotifyApp']['GetSettings']();
}

export function ImportLikedTracks(arg1) {
  return window['go']['main']['SpotifyApp']['ImportLikedTracks'](arg1);
}

export function Ping() {
  return window['go']['main']['SpotifyApp']['Ping']();
}

export function WebAuth() {
  return window['go']['main']['SpotifyApp']['WebAuth']();
}
