// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadArtists() {
  return window['go']['main']['YandexMusicApp']['DownloadArtists']();
}

export function DownloadPlaylists() {
  return window['go']['main']['YandexMusicApp']['DownloadPlaylists']();
}

export function GetArtists() {
  return window['go']['main']['YandexMusicApp']['GetArtists']();
}

export function GetPlaylists() {
  return window['go']['main']['YandexMusicApp']['GetPlaylists']();
}

export function ApplySettings(arg1) {
  return window['go']['main']['YandexMusicApp']['ApplySettings'](arg1);
}

export function DownloadAlbums() {
  return window['go']['main']['YandexMusicApp']['DownloadAlbums']();
}

export function GetAlbums() {
  return window['go']['main']['YandexMusicApp']['GetAlbums']();
}

export function GetSettings() {
  return window['go']['main']['YandexMusicApp']['GetSettings']();
}

export function GetTracks(arg1) {
  return window['go']['main']['YandexMusicApp']['GetTracks'](arg1);
}
